window.luxePick=(a,i)=>a[Math.max(0,Math.min(a.length-1,i))];
window.paletteFromValues=function(v){
  let bv=bucket(v.value),bc=bucket(v.chroma),bd=bucket(v.def),bh=bucket(v.hue),warm=v.temp>20,cool=v.temp<-20;
  let neutralHue=warm?35:cool?220:38,accentHue=warm?(bh>6?20:bh>4?58:170):cool?(bh<3?212:bh<6?330:155):(bh<4?210:bh>5?25:350);
  let neutralSat=10+bc*2,accentSat=24+bc*7,baseLight=20+bv*6,anchorLight=Math.max(8,baseLight-10-bd),lightNeutral=Math.min(92,baseLight+18);
  let lights=warm?['Ivory Silk','Oat Milk','Vanilla Cream','Cafe au Lait','Almond Milk','Champagne','Warm Latte','Biscotti','Honey Silk','Sunlit Cream']:cool?['Porcelain','Pearl','Moonstone','Dove Wing','Silver Mist','Cloud Gray','Frosted Silk','Ice Milk','Winter White','Blue Pearl']:['Ecru','Oyster','Parchment','Driftwood','Pebble','Mushroom','Sandstone','Greige','Soft Taupe','Stone Silk'];
  let neutrals=warm?['Cocoa','Saddle','Chestnut','Toffee','Caramel','Camel','Maple','Amber Tan','Burnished Honey','Golden Beige']:cool?['Graphite','Slate','Charcoal','Steel Blue','Storm Blue','Blue Gray','Pewter','Ash','Smoky Navy','Cool Navy']:['Taupe','Mink','Mushroom','Stone Brown','Hazelnut','Fawn','Greige','Mocha','Latte','Truffle'];
  let anchors=warm?['Espresso','Bark','Mahogany','Olive Brown','Coffee Bean','Dark Saddle','Cognac','Burnt Cinnamon','Bronze Olive','Sable']:cool?['Blackberry','Ink','Midnight','Deep Teal','Pine Shadow','Blue Black','Charcoal Navy','Plum Smoke','Evergreen','Onyx']:['Charcoal','Dark Olive','Earth Brown','Deep Moss','Umber','Root Beer','Smoked Plum','Bitter Chocolate','Storm Taupe','Granite'];
  let mains=warm?['Terracotta','Rosewood','Paprika','Coral Clay','Rust','Marigold','Moss','Olive','Lagoon Teal','Turquoise']:cool?['Berry','Rosewood','Raspberry','Plum','Cobalt','Sapphire','Pine','Emerald','Storm Teal','Iris']:['Burgundy','Dusty Rose','Denim','Petrol','Mauve','Mulberry','Sage','Olive Gray','Aubergine','Ocean'];
  let accents=warm?['Tomato Red','Coral','Apricot','Peach Silk','Marigold','Sunflower','Leaf Green','Jade','Lagoon','Aqua']:cool?['Ruby','Fuchsia','Orchid','Lavender','Cornflower','Cobalt','Teal','Jade','Mint','Aqua']:['Cranberry','Rose','Clay','Coral','Periwinkle','Denim Blue','Sea Green','Soft Teal','Sage','Aegean'];
  return [[luxePick(lights,bv),hslHex(neutralHue,neutralSat,lightNeutral)],[luxePick(neutrals,bv),hslHex(neutralHue,neutralSat+4,baseLight+5)],[luxePick(anchors,bd),hslHex(neutralHue,neutralSat+8,anchorLight)],[luxePick(mains,bc),hslHex(accentHue,accentSat,Math.min(78,38+bv*4))],[luxePick(accents,bh),hslHex((accentHue+38)%360,Math.min(92,accentSat+6),Math.min(80,42+bv*3))],[warm?'Antique Gold':cool?'Brushed Silver':'Mixed Metal',warm?'#d0a036':cool?'#c9d0d4':'#9aa0a4']];
};
