window.renderMixedQuiz=function(){
  const sw=cs=>`<span class="quiz-swatch-row">${cs.map(c=>`<i class="quiz-swatch" style="background:${c}"></i>`).join('')}</span>`;
  const card=(n,v,l,c,colors,chk='')=>`<label class="choice"><input type="radio" name="${n}" value="${v}" ${chk}><span class="box"><span class="name">${l}</span>${sw(colors)}<p class="desc">${c}</p></span></label>`;
  const range=(n,t,c,left,mid,right,val,colors)=>`<div class="range-card"><div class="range-head"><div><b>${t}</b><p class="desc">${c}</p>${sw(colors)}</div><span id="${n}Val">${val}</span></div><input type="range" name="${n}" min="0" max="100" value="${val}" oninput="document.querySelector('#${n}Val').textContent=this.value"><div class="range-labels"><span>${left}</span><span>${mid}</span><span>${right}</span></div></div>`;
  document.querySelector('#questions').innerHTML=`
  <div class="field"><div class="field-title">Quick setup <span>yes / no</span></div><p class="how">Check these before you start. They do not choose your palette, but they make the result more trustworthy.</p><div class="setup-grid">
    <label class="setup-card"><input type="checkbox" name="daylight" checked> <b>Daylight or bright natural light</b><span class="desc">Best for judging color.</span></label>
    <label class="setup-card"><input type="checkbox" name="noHeavyMakeup" checked> <b>No heavy makeup or fake tan</b><span class="desc">Keeps the read cleaner.</span></label>
    <label class="setup-card"><input type="checkbox" name="naturalHair" checked> <b>Natural roots or brows visible</b><span class="desc">Helpful if hair is colored.</span></label>
  </div></div>
  <div class="field"><div class="field-title">The White Shirt Test <span>pick one</span></div><p class="how">Hold white near the face, then cream. Which one makes the face look clearer and healthier?</p><div class="choices">${card('whiteCream','cool','White Wins','White looks cleaner; cream looks yellow or heavy.',['#ffffff','#f4f6fb','#dfe7f5'],'checked')}${card('whiteCream','warm','Cream Wins','Cream looks richer; white looks harsh or gray.',['#fff2d2','#f0dcad','#d7b377'])}${card('whiteCream','neutral','Both / Not sure','Both work, or the difference is small.',['#ffffff','#f2e5ca','#ddd8d0'])}</div><div class="confidence">${range('whiteConfidence','How obvious was it?','Use the slider like a confidence dial. Subtle means a small nudge; obvious means a strong signal.','Subtle','Clear','Obvious',55,['#f7f7f7','#ead9ba','#caa46f'])}</div></div>
  <div class="field"><div class="field-title">The Metal Test <span>pick one</span></div><p class="how">Compare gold and silver near the face. Which metal looks smoother and more natural?</p><div class="choices">${card('jewelry','cool','Silver Looks Better','Silver or pewter looks cleaner.',['#f7f7f5','#c9d0d4','#9aa0a4'],'checked')}${card('jewelry','warm','Gold Looks Better','Gold or bronze looks warmer.',['#fff0a0','#d0a036','#8a5d2f'])}${card('jewelry','neutral','Both Metals Work','Both metals look good.',['#c9d0d4','#d0a036','#9aa0a4'])}</div><div class="confidence">${range('metalConfidence','How obvious was it?','Move toward obvious only if one metal clearly wins.','Subtle','Clear','Obvious',55,['#c9d0d4','#d8c6a4','#d0a036'])}</div></div>
  <div class="field"><div class="field-title">Feature light/dark levels <span>sliders</span></div><p class="how">These are about light to dark, not race or undertone. Look at the full face.</p>${range('skinDepth','Skin Light/Dark Level','Look at the skin next to the hair and eyes.','Light','Medium','Deep',50,['#f4dfd2','#d8ad8f','#a56f52','#6a3f2f','#2f1d17'])}${range('hairDepth','Hair Light/Dark Level','Use roots, brows, or the most natural section.','Light','Medium','Deep',50,['#f3dfad','#b9854f','#6f452e','#2d211b','#0e0e0d'])}${range('eyeDepth','Eye Light/Dark Level','Do the eyes read bright, middle, or deep?','Light','Medium','Deep',50,['#b7d1d1','#98a471','#7a5a35','#3a2920','#151414'])}</div>
  <div class="field"><div class="field-title">Face contrast <span>slider</span></div>${range('contrastDepth','Light/Dark Contrast','Compare the lightest and darkest feature points. Are they close together or very different?','Soft','Balanced','Sharp',50,['#b8997c','#6d4a34','#10100f'])}</div>
  <div class="field"><div class="field-title">Color clues <span>pick lists</span></div><p class="how">Use daylight. Pick what you actually see in hair shine and eye flecks.</p><div class="choices">${card('hairHue','cool','Ash / Smoke','Cool reflection.',['#807d78','#5d6370','#1d2530'],'checked')}${card('hairHue','warm','Gold / Copper','Warm reflection.',['#c88437','#9b3f23','#7b4b2a'])}${card('hairHue','neutral','Hard to Tell','No clear direction.',['#8b7562','#56514b','#71685f'])}</div><div class="choices" style="margin-top:10px">${card('eyeHue','cool','Cool Flecks','Blue, slate, gray, or cool green.',['#7b9db4','#48596a','#366650'],'checked')}${card('eyeHue','warm','Warm Flecks','Gold, amber, copper, or olive.',['#a36d2e','#8a7b32','#b88a3d'])}${card('eyeHue','neutral','Mixed / Quiet','Mixed signals.',['#687064','#7a5c3d','#607b87'])}</div></div>`;
};
renderMixedQuiz();
if(document.querySelector('#sample'))document.querySelector('#sample').onclick=()=>{document.querySelector('#client').value='Sample Client';renderMixedQuiz();document.querySelector('[name=whiteCream][value=warm]').checked=true;document.querySelector('[name=jewelry][value=warm]').checked=true;document.querySelector('[name=hairHue][value=warm]').checked=true;document.querySelector('[name=eyeHue][value=warm]').checked=true;['skinDepth','hairDepth','eyeDepth','contrastDepth'].forEach((n,i)=>{let e=document.querySelector(`[name=${n}]`);e.value=[55,85,80,82][i];document.querySelector('#'+n+'Val').textContent=e.value});build()};
